spring:
  application:
    name: blogSummer

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: geooeg
    password: geo

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect